"""
signals/signal_engine.py — Signal engine: the heart of the bot
================================================================
Brings together all the pieces of the project to detect Adam Mancini's signals.

IMPROVEMENTS ADDED (June 2026):
  1. Active-trade state: blocks new signals until the trade closes.
  2. Management alerts: T1, T2, stop hit.
  3. Corrected trading windows: chop raises the bar (doesn't block), second
     window 3pm-4pm instead of 2pm-4pm.
  4. detect_failed_breakdown fixed: now detects intra-bar FB (when the flush
     and the recovery happen within the same 15-minute candle, a frequent
     case in high-volatility markets like today June 25 with a 96-pt elevator
     down in 14 minutes).
"""

import asyncio
import json
import textwrap  # to print the LLM's full reason across multiple lines
# import re  ← removed C-14: the JSON regexes were replaced by str.find/rfind
import sys
from datetime import datetime, timedelta
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

import anthropic
import pytz

from bot.telegram_alerts import TelegramAlerter

from config import (
    DATA_DIR,
    DATA_SOURCE,
    ANTHROPIC_API_KEY,
    LLM_MODEL,
    LLM_DECISION_MODEL,
    MIN_SIGNAL_CONFIDENCE,
    SPY_TO_ES_MULTIPLIER,
    LEVEL_TOLERANCE_POINTS,
    MARKET_TIMEZONE,
)

if DATA_SOURCE == 'ibkr':
    from market_data.ibkr_feed import ESFeed as MarketFeed, is_market_open
    print(f"📡 Feed: IBKR ES Futures (multiplier={SPY_TO_ES_MULTIPLIER})")
else:
    from market_data.alpaca_feed import SPYFeed as MarketFeed, is_market_open
    print(f"📡 Feed: Alpaca SPY (multiplier={SPY_TO_ES_MULTIPLIER})")


# ─────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────
TODAY_FILE  = DATA_DIR / 'daily' / 'today.json'
STATE_FILE  = DATA_DIR / 'signal_engine_state.json'
TWEETS_FILE = DATA_DIR / 'tweet_monitor_state.json'


# ─────────────────────────────────────────────
# Load the day's context
# ─────────────────────────────────────────────

def load_today() -> dict | None:
    """Loads the day map generated by the newsletter parser."""
    if not TODAY_FILE.exists():
        print("  ⚠️  today.json does not exist — run newsletter_parser.py first")
        return None

    with open(TODAY_FILE) as f:
        data = json.load(f)

    if data.get('date'):
        dias = (datetime.now().date() -
                datetime.strptime(data['date'], '%Y-%m-%d').date()).days
        if dias > 2:
            print(f"  ⚠️  today.json is {dias} day(s) old")

    if len(data.get('content_plan', '')) < 500:
        print("  ⚠️  content_plan too short — run newsletter_parser.py --force")

    return data


def get_all_levels(today: dict) -> list:
    """
    Extracts all of the day's levels (supports + resistances + pivot)
    and deduplicates them by numeric value.

    Resistances are included because of Adam's Level Reclaim setup.

    FIX B-5 — deduplication across lists:
    The LLM extractor (processor.py) sometimes classifies the same price as
    both a support AND a resistance (e.g. 7425 in the today.json of June 24).
    Without deduplicating, check_once queries the LLM TWICE for that level
    (once as support, once as resistance) and the prompt lists also mix
    types for the same price, confusing the model.

    CRITERION: if the same level (rounded to an integer) appears several times,
    we keep the FIRST occurrence in order: supports first, then resistances,
    then pivot. The type that 'wins' is the one the LLM extracted first,
    which is usually the most representative.
    """
    niveles = []
    for n in today.get('soportes', []):
        if n:
            niveles.append({'nivel': float(n), 'tipo': 'support'})
    for n in today.get('resistencias', []):
        if n:
            niveles.append({'nivel': float(n), 'tipo': 'resistance'})
    if today.get('nivel_critico'):
        nc = float(today['nivel_critico'])
        if not any(abs(x['nivel'] - nc) < 0.5 for x in niveles):
            niveles.append({'nivel': nc, 'tipo': 'pivot'})

    # Deduplicate by value rounded to the nearest integer.
    # round(7425.0) == round(7425.3) == 7425 → the first entry is kept.
    # This prevents the engine from querying the LLM twice for the same level
    # and the prompt from including contradictory types for the same price.
    vistos: dict[int, dict] = {}
    for entry in niveles:
        clave = round(entry['nivel'])
        if clave not in vistos:
            vistos[clave] = entry

    deduplicados = sorted(vistos.values(), key=lambda x: x['nivel'], reverse=True)

    n_total      = len(niveles)
    n_dedup      = len(deduplicados)
    if n_total != n_dedup:
        print(f"  🔧 B-5: {n_total - n_dedup} duplicate level(s) removed "
              f"({n_total} → {n_dedup})")

    return deduplicados


# ─────────────────────────────────────────────
# Adam's trading window
# ─────────────────────────────────────────────

def get_trading_window() -> tuple:
    """
    Determines which trading window we're in and the applicable criterion.

    Returns (hora_str, ventana_descripcion, criterio_extra_para_LLM).

    WINDOWS (per Adam's newsletter of June 24):
    - 7:30-11:00 AM: main, normal criterion
    - 11:00 AM-3:00 PM: chop — higher bar (NO automatic block)
      Only if: clear elevator down (25+ pts) + significant major low
    - 3:00-4:00 PM: real second window ("after 3pm")
    """
    tz_est   = pytz.timezone(MARKET_TIMEZONE)
    ahora    = datetime.now(tz_est)
    hora_str = ahora.strftime('%H:%M EST')
    hora_dec = ahora.hour + ahora.minute / 60.0

    if 7.5 <= hora_dec < 11.0:
        ventana  = "🟢 MAIN WINDOW (7:30-11:00 AM) — most of Adam's entries"
        criterio = (
            "We are in the MAIN WINDOW (7:30-11:00 AM). "
            "Normal criterion: evaluate the Failed Breakdown/Level Reclaim per the plan."
        )

    elif 11.0 <= hora_dec < 15.0:
        ventana  = "🟡 CHOP WINDOW (11:00 AM-3:00 PM) — higher bar, no hard block"
        criterio = (
            "We are in the CHOP WINDOW (11:00 AM-3:00 PM). "
            "Adam 'rarely' trades here — but it is NOT 'never'. "
            # B-7: removed example with a hardcoded date and prices ('June 25', 7409, 7415).
            # A specific example in the prompt anchors the LLM toward those concrete prices
            # and degrades decision quality as the days pass and the market range
            # drifts away from those values. The abstract rule is enough.
            "When he does trade in this window, it is always with a pronounced elevator down "
            "that flushes a significant major low, followed by a clear FB. "
            "He never enters chop at minor levels, resistances or already heavily tested zones."
            "\n\nELEVATED CRITERION — ALL of these requirements must be met:\n"
            "  1. CLEAR and recent elevator down (at least 25-30 pts in a fast drop)\n"
            "  2. The level is a SIGNIFICANT MAJOR LOW:\n"
            "     - Previous day's daily low, OR\n"
            "     - Multi-hour low (20+ pt drop that formed that low), OR\n"
            "     - Shelf of lows over several hours\n"
            "     Does NOT count: minor levels, resistances, 'tested to death' levels\n"
            "  3. Clear recovery of the level\n"
            "\nIf any one of these three is not clearly met → entrar: false."
        )

    elif 15.0 <= hora_dec < 16.0:
        ventana  = "🟠 SECOND WINDOW (3:00-4:00 PM) — only if the first trade was a winner"
        criterio = (
            "We are in the SECOND WINDOW (3:00-4:00 PM, 'after 3pm' per Adam). "
            "Only if the first trade of the day was a winner. "
            "Only with an A+ setup: clean elevator down + FB of a major level. "
            "Do NOT trade if Adam already closed his platform or is in runner mode."
        )

    else:
        ventana  = "⚪ OUTSIDE THE TRADING WINDOW"
        criterio = "OUTSIDE Adam's trading hours → entrar: false."

    return hora_str, ventana, criterio


# ─────────────────────────────────────────────
# The day's tweets
# ─────────────────────────────────────────────

def get_todays_tweets() -> list:
    """
    Reads Adam's tweets from today from TWO sources (monitor + scraper).

    FIX B-8 — timezone:
    It used to use local datetime.now() (Spain, UTC+2 in summer). Any of
    Adam's tweets after 18:00 EST (midnight in Spain) were compared against
    the NEXT day's date in Spain and got excluded, even though Adam is still
    mid-trading-session (until 16:00 EST).

    Now the 'trading day' is anchored to New York time (MARKET_TIMEZONE),
    like the rest of the bot's logic. And the tweets' UTC timestamps are
    converted to NY before comparing the date.
    """
    tz_ny = pytz.timezone(MARKET_TIMEZONE)   # America/New_York
    # 'today' in New York time — aligned with Adam's trading session
    hoy   = datetime.now(tz_ny).strftime('%Y-%m-%d')
    tweets     = []
    ids_vistos = set()

    if TWEETS_FILE.exists():
        try:
            state = json.load(open(TWEETS_FILE, encoding='utf-8'))
            # Note: tweet_monitor.py saves fecha_hoy in local time (Spain).
            # During market hours (07:30-16:00 EST = 13:30-22:00 Spain)
            # both dates coincide, so this comparison is correct.
            # The mismatch would only occur between 22:00 and midnight Spain
            # (16:00-18:00 EST, after-hours), where the tweets are history and
            # the past-words filter would reject them anyway.
            if state.get('fecha_hoy') == hoy:
                for item in state.get('tweets_hoy', []):
                    tweet = item.get('tweet', item) if isinstance(item, dict) else item
                    tid = tweet.get('id')
                    if tweet.get('text') and not tweet.get('is_retweet') and tid:
                        tweets.append(tweet)
                        ids_vistos.add(tid)
        except Exception:
            pass

    raw_file = DATA_DIR / 'raw' / 'tweets' / 'adam_mancini_tweets.json'
    if raw_file.exists():
        try:
            all_tweets = json.load(open(raw_file, encoding='utf-8'))
            for tweet in all_tweets:
                created = tweet.get('created_at', '')
                tid     = tweet.get('id')
                if not created or tweet.get('is_retweet') or tid in ids_vistos:
                    continue
                try:
                    # Parse Twitter's UTC timestamp and convert to NY time
                    # before comparing the date. This way '2026-06-26 22:30 UTC'
                    # (= 18:30 EST, after-close on the 26th) isn't classified as
                    # a tweet from the 27th just because it's already 00:30 on the 27th in Spain.
                    dt_utc = datetime.strptime(created, '%a %b %d %H:%M:%S +0000 %Y')
                    dt_ny  = pytz.utc.localize(dt_utc).astimezone(tz_ny)
                    if dt_ny.strftime('%Y-%m-%d') == hoy:
                        tweets.append(tweet)
                        ids_vistos.add(tid)
                except Exception:
                    pass
        except Exception:
            pass

    def _ts(t):
        try:
            # Sort by UTC timestamp (same basis for all tweets)
            dt_utc = datetime.strptime(t.get('created_at', ''), '%a %b %d %H:%M:%S +0000 %Y')
            return pytz.utc.localize(dt_utc)
        except Exception:
            return datetime.min.replace(tzinfo=pytz.utc)

    return sorted(tweets, key=_ts)


def formatear_tweets_para_prompt(tweets: list) -> str:
    """Format Adam's tweets from today for the LLM prompt."""
    if not tweets:
        return "No tweets from Adam yet today."
    lines = []
    for tweet in tweets[-12:]:
        texto = tweet.get('text', '').strip()
        if not texto:
            continue
        hora = ''
        created = tweet.get('created_at', '')
        if created:
            try:
                dt   = datetime.strptime(created, '%a %b %d %H:%M:%S +0000 %Y')
                hora = f" [{dt.strftime('%H:%M')} UTC]"
            except Exception:
                pass
        lines.append(f"• {texto}{hora}")
    return '\n'.join(lines) if lines else "No tweets from Adam yet today."


# ─────────────────────────────────────────────
# Level detection
# ─────────────────────────────────────────────

def is_price_at_level(precio_es: float, nivel: float, tolerancia: float = None) -> bool:
    """Is the ES price within tolerance of the level?"""
    tol = tolerancia or LEVEL_TOLERANCE_POINTS
    return abs(precio_es - nivel) <= tol


def determinar_lado(precio_es: float, nivel_info: dict, bias: str) -> str | None:
    """Adam never goes short → only 'long' or None."""
    tipo = nivel_info['tipo']
    if tipo in ('support', 'resistance', 'pivot'):
        if tipo == 'pivot' and precio_es < nivel_info['nivel']:
            return None
        return 'long' if bias != 'bearish' else None
    return None


def confirmar_con_vela_15min(bars_15: list, nivel: float, direccion: str) -> bool:
    """Technical confirmation with the last 15-minute candle."""
    if not bars_15:
        return False
    v     = bars_15[-1]
    m     = SPY_TO_ES_MULTIPLIER
    close = v['close'] * m
    open_ = v['open']  * m
    if direccion == 'long':
        return close > open_ and close >= nivel
    return False


def detect_failed_breakdown(bars_15: list, nivel: float) -> dict:
    """
    Detects the Failed Breakdown sequence at the level.

    REQUIRED CHRONOLOGICAL SEQUENCE:
      1. Price was ABOVE the level (+5 pts)
      2. Flush BELOW the level (-5 pts) — elevator down
      3. Current price recovered ABOVE — recovery

    FIX (June 2026) — INTRA-BAR FB:
      In very fast markets (like the 96-pt elevator down of June 25),
      the flush and the recovery can happen within the SAME 15min candle.
      The most recent bar has:
        - close > nivel (recovery)
        - low < nivel - 5 (intra-bar flush)

      The previous algorithm failed in this case because at i=1 it set
      was_above=True and then looked for the flush at i=2, i=3... without
      noticing that the flush was ALREADY at i=1 (in its low).

      FIX: we first check whether the most recent bar contains an intra-bar FB
      before running the standard loop.
    """
    if not bars_15 or len(bars_15) < 2:
        return {'es_fb': False, 'flush_size': 0, 'bars_ago': 0,
                'descripcion': 'Not enough candle data'}

    m                = SPY_TO_ES_MULTIPLIER
    precio_actual_es = bars_15[-1]['close'] * m

    # If the price is still below the level, the recovery hasn't happened yet
    if precio_actual_es <= nivel:
        return {'es_fb': False, 'flush_size': 0, 'bars_ago': 0,
                'descripcion': (f'Price {precio_actual_es:.0f} below '
                                f'{nivel:.0f} — recovery not completed yet')}

    # ── CHECK 1: intra-bar FB ─────────────────────────────────────────────
    barra_actual    = bars_15[-1]
    close_actual_es = barra_actual['close'] * m
    low_actual_es   = barra_actual['low']   * m

    if close_actual_es > nivel and low_actual_es < nivel - 5:
        precio_estaba_encima = any(
            b['close'] * m > nivel + 5
            for b in bars_15[-5:-1]
        )
        if precio_estaba_encima:
            flush_size = round(nivel - low_actual_es, 1)
            if flush_size >= 20:
                calidad = f'deep ({flush_size:.0f} pts) — high institutional probability'
            elif flush_size >= 10:
                calidad = f'moderate ({flush_size:.0f} pts)'
            else:
                calidad = f'shallow ({flush_size:.0f} pts)'
            return {
                'es_fb':       True,
                'flush_size':  flush_size,
                'bars_ago':    1,
                'descripcion': (
                    f'✅ INTRA-BAR FAILED BREAKDOWN: {calidad}, '
                    f'flush down to {low_actual_es:.0f} and recovery within the same candle, '
                    f'price {precio_actual_es:.0f} above {nivel:.0f}'
                )
            }

    # ── CHECK 2: standard FB (flush in a previous bar) ────────────────────
    was_above = False
    for i in range(1, min(9, len(bars_15))):
        bar      = bars_15[-i]
        close_es = bar['close'] * m
        low_es   = bar['low']   * m

        if not was_above:
            if close_es > nivel + 5:
                was_above = True
            continue

        if low_es < nivel - 5:
            flush_size = round(nivel - low_es, 1)
            if flush_size >= 20:
                calidad = f'deep ({flush_size:.0f} pts) — high institutional probability'
            elif flush_size >= 10:
                calidad = f'moderate ({flush_size:.0f} pts)'
            else:
                calidad = f'shallow ({flush_size:.0f} pts)'
            return {
                'es_fb':       True,
                'flush_size':  flush_size,
                'bars_ago':    i,
                'descripcion': (
                    f'✅ FAILED BREAKDOWN: {calidad}, {i} candles ago ({i*15} min), '
                    f'price {precio_actual_es:.0f} recovered above {nivel:.0f}'
                )
            }

    return {'es_fb': False, 'flush_size': 0, 'bars_ago': 0,
            'descripcion': (
                f'⚠️ No FB: price {precio_actual_es:.0f} above {nivel:.0f} '
                f'but no elevator down → flush → recovery sequence'
            )}


# ─────────────────────────────────────────────
# Signal generation with the LLM
# ─────────────────────────────────────────────

# ─────────────────────────────────────────────
# Mancini methodology — the cached "brain" (Phase 1)
# ─────────────────────────────────────────────
# The LLM now reasons from Adam's ACTUAL published methodology
# (knowledge_base/methodology/rubric.md, distilled from his fundamentals doc),
# not a hardcoded paraphrase. The rubric is static, so it is sent as a CACHED
# system block (cache_control: ephemeral) → ~0.1x cost after the first call.
# This is what restores his real "significant low" definition (range/cluster
# reclaims), the "flush size only sets acceptance needed" rule, the full
# acceptance protocol, and the Level Reclaim / back-test setups.
_METHODOLOGY_DIR = Path(__file__).parent.parent / 'knowledge_base' / 'methodology'
_RUBRIC_FILE = _METHODOLOGY_DIR / 'rubric.md'
_EXAMPLES_FILE = _METHODOLOGY_DIR / 'examples.md'
try:
    MANCINI_SYSTEM = _RUBRIC_FILE.read_text(encoding='utf-8')
except FileNotFoundError:
    MANCINI_SYSTEM = ("You are Adam Mancini trading ES futures. (Methodology rubric "
                      "missing — run scrapers/fetch_methodology.py to restore it.)")

# Phase 3 — append the reason-by-example few-shot block (real setups distilled
# from his own newsletter recaps) to the cached system prompt. It teaches the
# entry discrimination the abstract rubric alone missed live: take the deep
# Failed Breakdown of a genuine significant low; skip the mid-range /
# tested-to-death chop. Static → still one cached block.
if _EXAMPLES_FILE.exists():
    MANCINI_SYSTEM += "\n\n" + _EXAMPLES_FILE.read_text(encoding='utf-8')

# Dynamic per-signal user message. The methodology lives in the cached system
# prompt; this carries only TODAY's plan, TODAY's tweets, and the live situation.
SIGNAL_USER_PROMPT = """══════════════════════════════════════════════════════════
YOUR PLAN FOR TODAY (from today's newsletter):
══════════════════════════════════════════════════════════
{content_plan}

══════════════════════════════════════════════════════════
YOUR TWEETS FROM TODAY:
══════════════════════════════════════════════════════════
{tweets_hoy}

══════════════════════════════════════════════════════════
CURRENT SITUATION:
══════════════════════════════════════════════════════════
EST time:             {hora_est}
Current ES price:     {precio_es}
Level under analysis: {nivel} ({tipo_nivel})
Bias for the day:     {bias}

TRADING WINDOW RIGHT NOW:
{criterio_ventana}

FAILED BREAKDOWN ANALYSIS (from the structural detector):
{fb_descripcion}

15-MINUTE CANDLE: O:{open_15} H:{high_15} L:{low_15} C:{close_15}
Technical confirmation: {confirmacion}

══════════════════════════════════════════════════════════
DECIDE (apply your methodology from the system prompt):
══════════════════════════════════════════════════════════
1. Is this level ({nivel}) one of your pre-planned zones for today?
2. Is there a real Failed Breakdown (or Level Reclaim / back-test)? Check for a
   SIGNIFICANT low per your rules — prior-day low, multi-hour low, OR a
   cluster / multi-day range-low / S-R shelf that produced a strong bounce — a
   convincing flush (its SIZE only sets how much acceptance is needed), and
   acceptance on the reclaim.
3. Apply your time-window rules and the Mode 1 / Mode 2 context.
4. Do today's plan and tweets confirm or contraindicate it?
5. If bias is bearish, or this is chop / a "tested-to-death" level, the answer is
   usually NO trade. You never go short here.

STOP RULE: stop MUST be several points below the lowest low of the flush and
LOWER than entry (max 15 pts of risk).

Respond ONLY with valid JSON:
{{
  "entrar": true or false,
  "razon": "explain the setup: significant low + flush + acceptance, the window, and whether the plan/tweets support it",
  "entrada_es": number,
  "stop_es": number (LOWER than entrada_es, below the lowest low),
  "target1_es": number (next level above — where you take 75%),
  "target2_es": number or null,
  "confianza": 0.0 to 1.0
}}"""


async def generar_señal_llm(precio_es, nivel, tipo_nivel, direccion,
                      today, bars_15, fb_info=None, tweets=None,
                      criterio_ventana='') -> dict:
    """
    Asks Claude Haiku whether Adam would enter in this situation.

    FIX C-13 — async:
    client.messages.create() is synchronous and takes 1-3 s. Inside async
    it blocks ib_insync's event loop: no tick can be processed.
    asyncio.to_thread() runs the call in an OS thread and returns
    control to the event loop without stopping any other process.
    """
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    content_plan = (
        today.get('content_plan') or
        today.get('setup', '') + '\n' + today.get('invalida_si', '') or
        'Plan not available'
    )
    hora_est, _, _ = get_trading_window()

    if bars_15:
        v    = bars_15[-1]
        m    = SPY_TO_ES_MULTIPLIER
        open_15  = f"{v['open']  * m:.1f}"
        high_15  = f"{v['high']  * m:.1f}"
        low_15   = f"{v['low']   * m:.1f}"
        close_15 = f"{v['close'] * m:.1f}"
        confirmacion = ("YES — bullish candle confirms"
                        if confirmar_con_vela_15min(bars_15, nivel, direccion)
                        else "NO — candle does not confirm")
    else:
        open_15 = high_15 = low_15 = close_15 = f"{precio_es:.1f}"
        confirmacion = "No 15min candle data"

    user_prompt = SIGNAL_USER_PROMPT.format(
        content_plan     = content_plan,
        tweets_hoy       = formatear_tweets_para_prompt(tweets or []),
        hora_est         = hora_est,
        precio_es        = f"{precio_es:.1f}",
        nivel            = f"{nivel:.1f}",
        tipo_nivel       = tipo_nivel,
        bias             = today.get('bias', 'unknown'),
        criterio_ventana = criterio_ventana,
        fb_descripcion   = (fb_info or {}).get('descripcion', '⚠️ No analysis'),
        open_15          = open_15,
        high_15          = high_15,
        low_15           = low_15,
        close_15         = close_15,
        confirmacion     = confirmacion,
    )

    try:
        # C-13: to_thread frees ib_insync's event loop during the LLM call.
        # Phase 2: the DECISION runs on Sonnet 5 (LLM_DECISION_MODEL) with
        # adaptive thinking for sharper, more Mancini-faithful judgment. The
        # methodology rubric is a CACHED system block (Phase 1) → ~0.1x on repeat
        # calls. max_tokens is generous because the total output includes the
        # thinking tokens plus the reasoning `razon` + the closed JSON.
        response = await asyncio.to_thread(
            client.messages.create,
            model      = LLM_DECISION_MODEL,
            max_tokens = 2500,
            thinking   = {"type": "adaptive", "display": "summarized"},
            output_config = {"effort": "low"},
            system     = [{"type": "text", "text": MANCINI_SYSTEM,
                           "cache_control": {"type": "ephemeral"}}],
            messages   = [{"role": "user", "content": user_prompt}],
        )
        if response.stop_reason == 'max_tokens':
            print("  ⚠️  LLM hit max_tokens — response may be truncated")
        # Sonnet 5 returns thinking blocks before the answer — pull the TEXT
        # block, not content[0] (which may be a thinking block).
        text_block = next(
            (b.text for b in response.content if getattr(b, 'type', None) == 'text'),
            None,
        )
        if text_block is None:
            raise ValueError("No text block in the LLM response")
        raw = text_block.strip()
        # Fix JSON parsing: the LLM sometimes adds text before/after the JSON
        # causing 'Extra data' in json.loads. Extracting between the first '{'
        # and the last '}' ignores markdown and extra text.
        inicio = raw.find('{')
        fin    = raw.rfind('}')
        if inicio != -1 and fin != -1 and fin > inicio:
            raw = raw[inicio:fin + 1]
        else:
            raise ValueError(f"No JSON found in the LLM response: {raw[:200]}")
        resultado = json.loads(raw)

        # Mathematical validation: stop < entry for longs
        if resultado.get('entrar'):
            entrada = resultado.get('entrada_es')
            stop    = resultado.get('stop_es')
            if entrada and stop and float(stop) >= float(entrada):
                resultado['entrar'] = False
                resultado['razon']  = f"Discarded: stop ({stop}) >= entry ({entrada}) in LONG"

        return resultado
    except Exception as e:
        print(f"  ❌ LLM error: {e}")
        return {"entrar": False, "razon": f"Error: {e}"}


# ─────────────────────────────────────────────
# Motor principal
# ─────────────────────────────────────────────

# FIX C-10: cooldown constants in a single place.
# Previously the '60' was duplicated in _marcar_cooldown (twice) and
# _esta_en_cooldown (horas=1.0). Changing one without the others silently
# breaks the cooldown. With named constants there is a single source of truth.
COOLDOWN_SEÑAL_MIN    = 60   # minutes of cooldown after a signal is sent
COOLDOWN_NO_ENTRY_MIN = 15   # minutes of cooldown after the LLM rejects an entry

# Phase 1.3 — Failed-Breakdown acceptance/entry zone (points ABOVE the low).
# Adam does not enter while price is still ±3 pts "at" the flushed low; he waits
# for acceptance and enters when price sits ~5-15 pts above it (max risk 15).
# We therefore keep a level engageable while price is within this band above it
# AND a fresh FB has fired — so the bot keeps evaluating through the acceptance
# window instead of only at the flush.
FB_ENTRY_ZONE_PTS = 15.0

# Phase 4.A — deterministic level-ranking veto.
# The newsletter lists ~40 densely-packed supports, so a Failed Breakdown fires at
# many mid-range levels. Adam takes the DEEP FB of the day's significant low and
# skips the tested mid-range levels above it. We enforce that structurally, without
# spending an LLM call:
#   - DEEP_FLUSH_PTS: a flush this size marks a genuine significant-low FB
#     (matches detect_failed_breakdown's 'deep >= 20 = institutional' tier).
#   - MIDRANGE_BUFFER_PTS: how far ABOVE the established low a level must sit to be
#     treated as mid-range. Levels at/near/below the low still pass.
# This is the direct fix for the July 8 loss (7506/7511/7521 chop taken after the
# 7482 A+ low had already flushed and bounced).
DEEP_FLUSH_PTS = 20.0
MIDRANGE_BUFFER_PTS = 10.0


def update_significant_low(sig_low: dict | None, nivel: float, fb_info: dict) -> dict | None:
    """Return the day's significant low = the LOWEST level at which a DEEP Failed
    Breakdown (flush >= DEEP_FLUSH_PTS) has fired today.

    Set even if the bot did NOT take that trade — the structural detector still saw
    the A+ low form, which is exactly what was missed live on July 8. Pure function
    so the live engine and the backtest harness stay in lockstep.
    """
    if not fb_info.get('es_fb') or fb_info.get('flush_size', 0) < DEEP_FLUSH_PTS:
        return sig_low
    if sig_low is None or nivel < sig_low['price']:
        return {'price': float(nivel), 'flush': float(fb_info.get('flush_size', 0))}
    return sig_low


def is_midrange_chop_veto(nivel: float, fb_info: dict, sig_low: dict | None) -> bool:
    """True if this long candidate is tested mid-range chop above the day's
    established significant low, and should be suppressed WITHOUT an LLM call.

    Allowed (returns False): no significant low yet; the level is at/near/below the
    low (<= low + MIDRANGE_BUFFER_PTS); or a fresh DEEP flush fired at this level (a
    real setup, not chop). Applies to supports AND resistances (Level Reclaims).
    """
    if sig_low is None:
        return False
    if nivel <= sig_low['price'] + MIDRANGE_BUFFER_PTS:
        return False
    if fb_info.get('flush_size', 0) >= DEEP_FLUSH_PTS:
        return False
    return True


class SignalEngine:
    """
    Signal engine with active management of the open trade.

    ACTIVE-TRADE STATE (self._trade_activo):
    Once the signal is sent:
    {
        'direccion':     'long',
        'entrada':       float,
        'stop':          float,
        'stop_efectivo': float,   <- moved to breakeven after T1
        't1':            float,
        't2':            float | None,
        'nivel':         float,
        'hora':          datetime,
        't1_alcanzado':  bool,
        't2_alcanzado':  bool,
    }
    While there is an active trade, NO new entries are sought.
    """

    def __init__(self):
        self.feed    = MarketFeed()
        # C-11: alerter as an attribute — a single instance reused across all
        # events (entry, T1, T2, stop).
        self.alerter = TelegramAlerter()
        self._trade_activo: dict | None = None
        self._last_signal: dict = {}
        # Phase 4.A — per-day state. `_dia` anchors the daily reset; `_significant_low`
        # is the day's deepest Failed-Breakdown low used by the mid-range veto.
        self._dia: str | None = None
        self._significant_low: dict | None = None
        # Phase 4.B — day-state machine enforcing Adam's trade-discipline rules
        # (from his methodology): 1–3 trades/day; first WIN → stop until the post-2pm
        # session; first non-win → exactly one retry ("try a second but never more").
        self._trades_hoy: int = 0
        self._resultados_hoy: list[str] = []      # ordered 'win'/'loss'/'scratch'
        self._primer_resultado: str | None = None  # result of trade #1
        # Restore the trade and cooldowns from a previous session if they exist on disk.
        self._cargar_estado()

    def _reset_day_state_if_new_day(self, hoy: str):
        """Clear per-day state (significant low + trade discipline) on a new NY day."""
        if self._dia != hoy:
            self._dia = hoy
            self._significant_low = None
            self._trades_hoy = 0
            self._resultados_hoy = []
            self._primer_resultado = None

    def _registrar_resultado_trade(self, result: str):
        """Record a closed trade's outcome for the day-state rules (Phase 4.B).

        'win' is banked when T1 is reached (stop is at breakeven from then on, so
        the trade can no longer turn red). 'loss' = stopped before T1. 'scratch' =
        timed out before T1. Only the first result seeds `_primer_resultado`.
        """
        self._resultados_hoy.append(result)
        if self._primer_resultado is None:
            self._primer_resultado = result
        print(f"  📒 Day state: trade result '{result}' recorded — "
              f"{self._trades_hoy} trade(s) today, first={self._primer_resultado}")

    def _entrada_permitida_por_estado(self, hora_dec: float) -> tuple[bool, str]:
        """Adam's deterministic trade-count / outcome gate (Phase 4.B).

        Returns (allowed, reason_if_blocked). Applied BEFORE engaging levels, so a
        day that is 'done' costs no LLM calls.
        """
        n = self._trades_hoy
        if n >= 3:
            return False, "daily hard cap (3 trades) reached — done for the day"
        if n == 0:
            return True, ""
        if self._primer_resultado == 'win':
            # "If the first trade is a win, I will wrap it up until the post-2pm session."
            if hora_dec < 14.0:
                return False, "first trade WON — wrapping up until the post-2pm session"
            return True, ""
        # First trade was a loss/scratch: "try a second but never more."
        if n >= 2:
            return False, "already took the second trade after a non-win — 'never more'"
        return True, ""

    # ─────────────────────────────────────────────
    # State persistence on disk (A-2)
    # ─────────────────────────────────────────────

    def _guardar_estado(self):
        """Dumps the active trade and the per-level cooldowns to disk."""
        try:
            trade = None
            if self._trade_activo:
                trade = dict(self._trade_activo)
                if isinstance(trade.get('hora'), datetime):
                    trade['hora'] = trade['hora'].isoformat()
            data = {
                'guardado_en':  datetime.now().isoformat(),
                'trade_activo': trade,
                'last_signal':  {k: v.isoformat() for k, v in self._last_signal.items()},
                # Phase 4.A/4.B — per-day state (restored only if same NY day)
                'dia':               self._dia,
                'significant_low':   self._significant_low,
                'trades_hoy':        self._trades_hoy,
                'resultados_hoy':    self._resultados_hoy,
                'primer_resultado':  self._primer_resultado,
            }
            STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
            with open(STATE_FILE, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
        except Exception as e:
            print(f"  ⚠️  Could not save the engine state: {e}")

    def _cargar_estado(self):
        """Restores the state from STATE_FILE at startup, with age guards."""
        if not STATE_FILE.exists():
            return
        try:
            with open(STATE_FILE, encoding='utf-8') as f:
                data = json.load(f)
        except Exception as e:
            print(f"  ⚠️  Could not read the saved state: {e}")
            return

        ahora = datetime.now()

        # ── Active trade (with age guards) ────────────────────────────
        trade = data.get('trade_activo')
        if trade and trade.get('hora'):
            try:
                hora_trade   = datetime.fromisoformat(trade['hora'])
                antiguedad_h = (ahora - hora_trade).total_seconds() / 3600
                mismo_dia    = hora_trade.date() == ahora.date()
                if antiguedad_h < 3 and mismo_dia:
                    trade['hora'] = hora_trade
                    self._trade_activo = trade
                    print(f"  🔄 Active trade restored: entry {trade.get('entrada')} | "
                          f"T1 {'✓' if trade.get('t1_alcanzado') else '✗'} | "
                          f"stop {trade.get('stop_efectivo')}")
                else:
                    print(f"  🗑️  Saved trade discarded "
                          f"(age {antiguedad_h:.1f}h, same_day={mismo_dia})")
            except Exception:
                pass

        # ── Cooldowns still active (C-10: stores expiry, not start) ──
        for nivel_str, ts_str in (data.get('last_signal') or {}).items():
            try:
                expiry = datetime.fromisoformat(ts_str)
                if expiry > ahora:
                    self._last_signal[nivel_str] = expiry
            except Exception:
                pass

        # ── Phase 4.A/4.B — per-day state, same NY day only ──
        try:
            hoy_ny = datetime.now(pytz.timezone(MARKET_TIMEZONE)).strftime('%Y-%m-%d')
            if data.get('dia') == hoy_ny:
                self._dia = data['dia']
                self._significant_low = data.get('significant_low')
                self._trades_hoy = data.get('trades_hoy', 0)
                self._resultados_hoy = data.get('resultados_hoy', []) or []
                self._primer_resultado = data.get('primer_resultado')
                if self._significant_low:
                    print(f"  🎯 Significant low restored: "
                          f"{self._significant_low['price']:.0f} "
                          f"(flush {self._significant_low['flush']:.0f})")
                if self._trades_hoy:
                    print(f"  📒 Day state restored: {self._trades_hoy} trade(s), "
                          f"first={self._primer_resultado}")
        except Exception:
            pass

    async def _gestionar_trade_activo(self, precio_es: float) -> str:
        """
        Monitors T1, T2, stop and timeout of the active trade.
        Returns 'bloqueado' if the trade is open, 'libre' if closed.

        FIX A-3: uses high/low of 1-min candles to detect touches that the
        spot price (delayed 15 min, sampled every 60s) would miss.
        T1 is checked BEFORE the stop: if both happen in the same bar,
        T1 wins → green day ('first trade is a win').
        """
        if not self._trade_activo:
            return 'libre'

        trade     = self._trade_activo
        entrada   = trade['entrada']
        t1        = trade['t1']
        t2        = trade.get('t2')
        stop_ef   = trade['stop_efectivo']
        direccion = trade['direccion']

        if direccion != 'long':
            self._trade_activo = None
            return 'libre'

        # ── A-3: real high and low of the last 3 1-min candles ──────────────
        alto_reciente = precio_es
        bajo_reciente = precio_es
        try:
            bars_1m = await self.feed.get_bars(1, 3)
            if bars_1m:
                m             = SPY_TO_ES_MULTIPLIER
                alto_reciente = max(b['high'] * m for b in bars_1m)
                bajo_reciente = min(b['low']  * m for b in bars_1m)
        except Exception:
            pass

        # ── T2 ────────────────────────────────────────────────────────────────
        if trade.get('t1_alcanzado') and t2 and not trade.get('t2_alcanzado'):
            if alto_reciente >= float(t2):
                trade['t2_alcanzado'] = True
                print(f"  🏆 T2 reached: {t2}")
                await self.alerter.send_t2_alert(trade, alto_reciente)
                self._trade_activo = None
                return 'libre'

        # ── T1 (before the stop) ──────────────────────────────────────────────
        if not trade.get('t1_alcanzado') and alto_reciente >= float(t1):
            trade['t1_alcanzado']  = True
            trade['stop_efectivo'] = entrada
            print(f"  ✅ T1 reached: {t1}")
            await self.alerter.send_t1_alert(trade, alto_reciente)
            # Phase 4.B — bank the WIN now: stop is at breakeven from here, so the
            # trade can no longer turn red ("first trade is a win").
            self._registrar_resultado_trade('win')

        # ── Effective stop ───────────────────────────────────────────────────
        if bajo_reciente <= stop_ef:
            print(f"  🛑 Stop hit: {bajo_reciente:.0f}")
            await self.alerter.send_stop_alert(trade, bajo_reciente)
            # Phase 4.B — a stop BEFORE T1 is a loss; a breakeven stop after T1 was
            # already banked as a win above.
            if not trade.get('t1_alcanzado'):
                self._registrar_resultado_trade('loss')
            self._trade_activo = None
            return 'libre'

        # ── 3-hour timeout ────────────────────────────────────────────────────
        if (datetime.now() - trade['hora']).total_seconds() / 3600 >= 3:
            print(f"  ⏰ Trade expired (3h) — releasing")
            # Phase 4.B — timed out before T1 = scratch (neither win nor loss).
            if not trade.get('t1_alcanzado'):
                self._registrar_resultado_trade('scratch')
            self._trade_activo = None
            return 'libre'

        pts      = precio_es - entrada
        signo    = '+' if pts >= 0 else ''
        t1_label = '✅ T1✓ runner' if trade.get('t1_alcanzado') else f'→T1:{t1:.0f}'
        print(f"  📊 Active trade: {entrada:.0f} → {precio_es:.1f} "
              f"({signo}{pts:.0f}pts) | "
              f"H:{alto_reciente:.0f} L:{bajo_reciente:.0f} | "
              f"{t1_label} | stop:{stop_ef:.0f}")
        return 'bloqueado'

    def _esta_en_cooldown(self, nivel: float) -> bool:
        """True if the level is still in cooldown (C-10: direct expiry)."""
        key    = f"{nivel:.0f}"
        expiry = self._last_signal.get(key)
        if expiry is None:
            return False
        return datetime.now() < expiry

    def _marcar_cooldown(self, nivel: float, minutos: int):
        """Puts the level in cooldown for 'minutos' minutes from now (C-10)."""
        self._last_signal[f"{nivel:.0f}"] = datetime.now() + timedelta(minutes=minutos)

    def _log_near_miss(self, nivel, tipo_nivel, precio_es, señal, fb_info, kind):
        """
        Phase 2 — record setups we ALMOST took (calibration data).

        'kind' is 'low_confidence' (model said enter but below the confidence
        threshold) or 'high_conf_reject' (model said no but with ≥0.5 conviction).
        Appended as JSON lines to data/near_misses.jsonl for later review — this
        is the raw material for tuning the threshold and the methodology.
        """
        try:
            rec = {
                'ts':        datetime.now().isoformat(),
                'kind':      kind,
                'nivel':     nivel,
                'tipo':      tipo_nivel,
                'precio_es': round(float(precio_es), 2),
                'entrar':    señal.get('entrar'),
                'confianza': señal.get('confianza'),
                'razon':     señal.get('razon', ''),
                'fb':        (fb_info or {}).get('descripcion', ''),
            }
            with open(DATA_DIR / 'near_misses.jsonl', 'a', encoding='utf-8') as f:
                f.write(json.dumps(rec, ensure_ascii=False) + '\n')
        except Exception:
            pass

    async def check_once(self) -> bool:
        """Full market-check cycle (every 60s)."""
        snapshot = self.feed.get_snapshot()
        if not snapshot:
            return False

        precio_es = snapshot['es_equivalent']
        ahora     = snapshot['timestamp'][:19]

        # Phase 4.A — reset per-day state at the NY day boundary.
        hoy_ny = datetime.now(pytz.timezone(MARKET_TIMEZONE)).strftime('%Y-%m-%d')
        self._reset_day_state_if_new_day(hoy_ny)

        estado_trade = await self._gestionar_trade_activo(precio_es)
        self._guardar_estado()  # A-2: captures T1→breakeven and closes

        today = load_today()
        if not today:
            return False

        niveles  = get_all_levels(today)
        bias     = today.get('bias', 'unknown')

        niveles_cercanos = [
            n for n in niveles
            if abs(n['nivel'] - precio_es) <= 60
        ]

        hora_est, ventana, criterio_ventana = get_trading_window()

        if DATA_SOURCE == 'ibkr':
            print(f"[{ahora}] ES:{precio_es:.1f} | "
                  f"Bias:{bias} | {hora_est} | Nearby levels:{len(niveles_cercanos)}")
        else:
            spy_price = snapshot.get('spy_price', precio_es / 10)
            print(f"[{ahora}] SPY:{spy_price:.2f} ES:{precio_es:.1f} | "
                  f"Bias:{bias} | {hora_est} | Nearby levels:{len(niveles_cercanos)}")

        tweets_hoy = get_todays_tweets()
        if tweets_hoy:
            print(f"  🐦 {len(tweets_hoy)} tweets from Adam today")

        if estado_trade == 'bloqueado':
            return False

        # Phase 4.B — deterministic day-state gate (Adam's trade-count / outcome
        # rules). Checked before engaging any level, so a day that is already "done"
        # (first win, or the retry after a loss used up, or the 3-trade cap) costs
        # zero LLM calls.
        ahora_ny = datetime.now(pytz.timezone(MARKET_TIMEZONE))
        hora_dec = ahora_ny.hour + ahora_ny.minute / 60.0
        puede_operar, motivo = self._entrada_permitida_por_estado(hora_dec)
        if not puede_operar:
            print(f"  🚫 No new entries: {motivo} "
                  f"[trades={self._trades_hoy}, first={self._primer_resultado}]")
            return False

        señal_enviada = False

        # B-6: 15-min candles once before the loop
        bars_15: list = []
        if niveles_cercanos:
            try:
                bars_15 = await self.feed.get_bars(15, 8)
            except Exception as e:
                print(f"  ⚠️  Error fetching 15min candles: {e}")

        # Phase 4.A — pre-pass: establish the day's significant low from ALL nearby
        # levels (even ones we won't engage) so the mid-range veto has its anchor
        # within the same tick, independent of level ordering. FB results are cached
        # and reused below to avoid recomputing detect_failed_breakdown.
        prev_low = self._significant_low['price'] if self._significant_low else None
        fb_by_level: dict[float, dict] = {}
        for nivel_info in niveles_cercanos:
            fb = detect_failed_breakdown(bars_15, nivel_info['nivel'])
            fb_by_level[nivel_info['nivel']] = fb
            self._significant_low = update_significant_low(
                self._significant_low, nivel_info['nivel'], fb)
        if self._significant_low and self._significant_low['price'] != prev_low:
            veto_above = self._significant_low['price'] + MIDRANGE_BUFFER_PTS
            print(f"  🎯 Day significant low established: "
                  f"{self._significant_low['price']:.0f} "
                  f"(deep flush {self._significant_low['flush']:.0f} pts) — "
                  f"shallow-flush longs above {veto_above:.0f} now vetoed")

        for nivel_info in niveles_cercanos:
            nivel      = nivel_info['nivel']
            tipo_nivel = nivel_info['tipo']

            fb_info = fb_by_level[nivel]

            # Phase 1.3 — engagement zone. Engage the LLM when price is AT the
            # level (±tolerance: first touch / back-test / level reclaim) OR when
            # a fresh Failed Breakdown has fired and price is in the acceptance /
            # entry zone just ABOVE the low (where Adam actually enters). Without
            # this the bot only looked at the flush (too early — "no acceptance
            # yet") and stopped watching before the real entry formed.
            at_level   = is_price_at_level(precio_es, nivel)
            en_zona_fb = fb_info['es_fb'] and (0 < precio_es - nivel <= FB_ENTRY_ZONE_PTS)
            if not (at_level or en_zona_fb):
                continue
            if self._esta_en_cooldown(nivel):
                continue

            direccion = determinar_lado(precio_es, nivel_info, bias)
            if not direccion:
                continue

            # Phase 4.A — deterministic mid-range chop veto (no LLM spend). Once the
            # day's significant low is in, a tested higher level with only a shallow
            # flush is the chop Adam avoids — suppress it before querying the model.
            if is_midrange_chop_veto(nivel, fb_info, self._significant_low):
                print(f"  ⛔ Mid-range veto: {nivel:.0f} ({tipo_nivel}) sits above "
                      f"significant low {self._significant_low['price']:.0f} with a "
                      f"shallow flush ({fb_info.get('flush_size', 0):.0f} pts) — "
                      f"suppressed, no LLM call")
                self._log_near_miss(
                    nivel, tipo_nivel, precio_es,
                    {'entrar': None, 'confianza': None,
                     'razon': (f"mid-range chop above significant low "
                               f"{self._significant_low['price']:.0f}")},
                    fb_info, 'midrange_veto')
                self._marcar_cooldown(nivel, minutos=COOLDOWN_NO_ENTRY_MIN)
                continue

            print(f"  {'✅ FB' if fb_info['es_fb'] else '⚠️  No FB'} | "
                  f"Level:{nivel:.0f} ({tipo_nivel}) | "
                  f"{fb_info['descripcion'][:70]}")

            confirmado = confirmar_con_vela_15min(bars_15, nivel, direccion)
            print(f"  📊 {direccion.upper()} | "
                  f"15min: {'✅' if confirmado else '⚠️'} | "
                  f"Window: {ventana[:45]}")

            print("  🤖 Querying LLM...")
            # C-13: generar_señal_llm is now async — uses asyncio.to_thread internally
            señal = await generar_señal_llm(
                precio_es        = precio_es,
                nivel            = nivel,
                tipo_nivel       = tipo_nivel,
                direccion        = direccion,
                today            = today,
                bars_15          = bars_15,
                fb_info          = fb_info,
                tweets           = tweets_hoy,
                criterio_ventana = criterio_ventana,
            )
            señal['direccion'] = direccion

            confianza = float(señal.get('confianza', 0) or 0)
            entrar    = bool(señal.get('entrar'))

            if entrar and confianza >= MIN_SIGNAL_CONFIDENCE:
                print(f"  ✅ LLM: ENTER ({confianza:.0%} confidence)")

                # C-11: send_signal_alert (escaped HTML, computed R/R)
                await self.alerter.send_signal_alert(señal, precio_es, nivel, today)

                self._trade_activo = {
                    'direccion':     direccion,
                    'entrada':       float(señal.get('entrada_es', nivel)),
                    'stop':          float(señal.get('stop_es', nivel - 15)),
                    'stop_efectivo': float(señal.get('stop_es', nivel - 15)),
                    't1':            float(señal.get('target1_es', nivel + 20)),
                    't2':            float(señal['target2_es']) if señal.get('target2_es') else None,
                    'nivel':         nivel,
                    'hora':          datetime.now(),
                    't1_alcanzado':  False,
                    't2_alcanzado':  False,
                }
                # Phase 4.B — count this trade toward the day's cap. The outcome
                # (win/loss/scratch) is recorded later when the trade closes.
                self._trades_hoy += 1
                print(f"  🔒 Active trade — new entries blocked "
                      f"(trade #{self._trades_hoy} today)")

                self._marcar_cooldown(nivel, minutos=COOLDOWN_SEÑAL_MIN)
                señal_enviada = True
                break

            elif entrar:
                # Phase 2 — the model wants in but conviction is below threshold.
                # Adam only takes 100%-conviction setups, so we SUPPRESS the alert
                # and record it as a near-miss for calibration.
                print(f"  ⚠️  LLM: enter but LOW confidence "
                      f"({confianza:.0%} < {MIN_SIGNAL_CONFIDENCE:.0%}) — suppressed")
                self._log_near_miss(nivel, tipo_nivel, precio_es, señal, fb_info, 'low_confidence')
                self._marcar_cooldown(nivel, minutos=COOLDOWN_NO_ENTRY_MIN)

            else:
                # Print the LLM's FULL reason (it used to be truncated to 100 chars).
                # It's formatted across multiple lines so it's readable in the console.
                razon = señal.get('razon', '')
                lineas = textwrap.wrap(razon, width=95)
                print(f"  ❌ LLM: Do not enter — {lineas[0] if lineas else ''}")
                for linea in lineas[1:]:
                    print(f"                     {linea}")
                # Phase 2 — log high-confidence rejects too: the model was close,
                # which is exactly the calibration signal we want to review.
                if confianza >= 0.5:
                    self._log_near_miss(nivel, tipo_nivel, precio_es, señal, fb_info, 'high_conf_reject')
                self._marcar_cooldown(nivel, minutos=COOLDOWN_NO_ENTRY_MIN)

        # A-2: persist at the end of the tick
        self._guardar_estado()
        return señal_enviada

    async def run_loop(self, interval_seconds: int = 60):
        """Main loop: checks the market every 60 seconds."""
        print("=" * 55)
        print("  Adam Mancini Bot — Signal Engine")
        print("=" * 55)
        print(f"⏱️  Interval: {interval_seconds}s | Tolerance: ±{LEVEL_TOLERANCE_POINTS}pts ES")
        print("Ctrl+C to stop\n")

        if DATA_SOURCE == 'ibkr' and hasattr(self.feed, 'connect_async'):
            try:
                await self.feed.connect_async()
            except Exception as e:
                print(f"\n❌ Could not connect to IBKR: {e}")
                return

        try:
            while True:
                if not is_market_open():
                    tz    = pytz.timezone(MARKET_TIMEZONE)
                    ahora = datetime.now(tz).strftime('%H:%M')
                    print(f"[{ahora}] 😴 Market closed — waiting 5 min")
                    await asyncio.sleep(300)
                    continue

                await self.check_once()
                await asyncio.sleep(interval_seconds)

        finally:
            if DATA_SOURCE == 'ibkr' and hasattr(self.feed, 'disconnect'):
                self.feed.disconnect()


if __name__ == '__main__':
    engine = SignalEngine()
    try:
        asyncio.run(engine.run_loop(interval_seconds=60))
    except KeyboardInterrupt:
        print("\n⏹️  Engine stopped")
